// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe01uUsny8xInVUokz3_y21lN1RA3ANuw',
    appId: '1:99713058396:android:bf0b233c5fe65ba71b8899',
    messagingSenderId: '99713058396',
    projectId: 'fireapp-3cd0b',
    databaseURL: 'https://fireapp-3cd0b-default-rtdb.firebaseio.com',
    storageBucket: 'fireapp-3cd0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6kTxBCJ4kknzNAdE23Rn2CICv9Zfdtgo',
    appId: '1:99713058396:ios:cb7317db0f2e00e71b8899',
    messagingSenderId: '99713058396',
    projectId: 'fireapp-3cd0b',
    databaseURL: 'https://fireapp-3cd0b-default-rtdb.firebaseio.com',
    storageBucket: 'fireapp-3cd0b.appspot.com',
    iosBundleId: 'com.example.vocabularyNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6kTxBCJ4kknzNAdE23Rn2CICv9Zfdtgo',
    appId: '1:99713058396:ios:cb7317db0f2e00e71b8899',
    messagingSenderId: '99713058396',
    projectId: 'fireapp-3cd0b',
    databaseURL: 'https://fireapp-3cd0b-default-rtdb.firebaseio.com',
    storageBucket: 'fireapp-3cd0b.appspot.com',
    iosBundleId: 'com.example.vocabularyNote',
  );
}
