default_platform(:android)

platform :android do
  desc "Lane for android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:428522521690:android:3f2e8509a42b23ecc0c463"      ,
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],	
      android_artifact_type: "APK" ,
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "abdo.agiry90@gmail.com , essamhamdy12345@gmail.com",
      release_notes: "First Fastlane Firebase App Distribution"
    )
  end
end
